---
splunk_server:
  url: http://download.splunk.com/releases/6.2.3/splunk/linux/splunk-6.2.3-264376-Linux-x86_64.tgz
  downloaded_path: /tmp/splunk-6.2.3-264376-Linux-x86_64.tgz
  expected_version: Splunk 6.2.3 (build 264376)
  install_dir: /app/splunk
  parent_dir: /app

  group:
    name: splunk
    gid: 396

  user:
    name: splunk
    uid: 396
    shell: /bin/bash
    comment: Splunk Service
    group: splunk

