---
- name: "Download Splunk Forwarder package"
  get_url: url={{ splunk_forwarder.url }} dest={{ splunk_forwarder.downloaded_path }}

- name: "Ensure Splunk Forwarder folder exists"
  sudo: yes
  file: path={{ splunk_forwarder.parent_dir }}
    state=directory

- name: "Unpack Splunk Forwarder"
  command: "tar --directory {{ splunk_forwarder.parent_dir }} -xzf {{ splunk_forwarder.downloaded_path }}"
  sudo: yes

- name: "run install script"
  sudo: yes
  script: splunkforwarder.install {{ splunk_forwarder.install_dir }} 

- name: "Delete downloaded splunk forwarder package"
  file: path={{ splunk_forwarder.downloaded_path }} state=absent

