---
splunk_server:
  app_repo:
    branch: new-deployment-strategy
    parent_path: /app/git
    install_path: /app/git/splunk-deployment-apps
    url: git@gitlab.services.ecetera.com.au:techtalks/techtalk-test-aws-terraform-ansible-splunkapps.git

  ssh_files:
    - src: ssh_config/splunkapps_deploy.key
      dest: /home/splunk/.ssh/splunkapps_deploy.key
      owner: splunk
      group: splunk
      mode: "0600"
    - src: ssh_config/splunkapps_deploy.key.pub
      dest: /home/splunk/.ssh/splunkapps_deploy.key.pub
      owner: splunk
      group: splunk
      mode: "0644"
    - src: ssh_config/config
      dest: /home/splunk/.ssh/config
      owner: splunk
      group: splunk
      mode: "0644"
