---
splunk_server:
  app_repo:
    branch: master
    parent_path: /app/git
    install_path: /app/git/splunk-deployment-apps
    url: ssh://git@gitlab.services.ecetera.com.au/target/splunk-upgrade-poc.git
