---
- name: Ensure index dir exists
  sudo: yes
  file: path=/app/splunk-index
    state=directory
    owner={{ splunk_server.user.name }}
    group={{ splunk_server.group.name }}
    mode="0755"

- name: configure deployment server
  sudo: yes
  template: src=serverclass.conf
    dest={{ splunk_server.install_dir }}/etc/system/local/serverclass.conf
    owner={{ splunk_server.user.name }}
    group={{ splunk_server.group.name }}
    mode=0644
  notify: restart splunk

- name: Ensure git repo dir exists
  sudo: yes
  file: path={{ splunk_server.app_repo.parent_path }}
    state=directory
    owner={{ splunk_server.user.name }}
    group={{ splunk_server.group.name }}
    mode="0755"

- name: Install git
  sudo: yes
  apt: name=git state=present

- name: Setup required folders for SSH
  sudo: yes
  file: path="/home/{{splunk_server.user.name}}/.ssh"
    state=directory
    owner={{ splunk_server.user.name }}
    group={{ splunk_server.group.name }}
    mode="0700"

- name: Setup SSH deployment keys
  sudo: yes
  copy: src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items: splunk_server.ssh_files

- name: Pull down Splunk apps
  sudo: yes
  sudo_user: "{{ splunk_server.user.name }}"
  git: repo={{ splunk_server.app_repo.url }}
    version={{ splunk_server.app_repo.branch }}
    dest={{ splunk_server.app_repo.install_path }}
    accept_hostkey=yes
    force=yes
  register: splunk_repo
  notify: restart splunk

- name: Install Splunk apps locally
  sudo: yes
  sudo_user: "{{ splunk_server.user.name }}"
  shell: "cp -R {{ splunk_server.app_repo.install_path }}/* {{ splunk_server.install_dir }}/etc/apps/"
  when: splunk_repo.changed == true
  notify: restart splunk

